clusterName: hbang-proxmox
namespace: default
kubernetesVersion: "v1.34.3"

proxmoxCluster:
  controlPlaneEndpoint:
    host: "192.168.1.200"
    port: 6443
  dnsServers:
  - 8.8.8.8
  - 1.1.1.1
  ipv4:
    addresses:
    - "192.168.1.100-192.168.1.127"
    gateway: "192.168.1.254"
    prefix: 24


worker:
  machines:
    hbang-px1:
      templateID: 113
      replicas: 2
      numCores: 4
      numSockets: 1
      memoryMiB: 16384
      diskSizeGb: 100
      format: raw
      fullClone: true
      network:
        bridge: vmbr0
        model: virtio
    hbang-px2:
      templateID: 115
      replicas: 2
      numCores: 4
      numSockets: 1
      memoryMiB: 16384
      diskSizeGb: 100
      format: raw
      fullClone: true
      network:
        bridge: vmbr0
        model: virtio
    hbang-px3:
      templateID: 114
      replicas: 2
      numCores: 4
      numSockets: 1
      memoryMiB: 16384
      diskSizeGb: 100
      format: raw
      fullClone: true
      network:
        bridge: vmbr0
        model: virtio


clusterNetwork:
  pods:
    cidrBlocks:
    - "192.168.0.0/16"

kubeadm:
  users:
  - name: root
    sshAuthorizedKeys: []
