clusterName: hbang-proxmox
namespace: default
kubernetesVersion: "v1.32.4"

proxmoxCluster:
  controlPlaneEndpoint:
    host: "192.168.1.200"
    port: 6443
  dnsServers:
  - 8.8.8.8
  - 1.1.1.1
  ipv4:
    addresses:
    - "192.168.1.100-192.168.1.127"
    gateway: "192.168.1.254"
    prefix: 24

controlPlane:
  # unfortuneately, provisioning multiple controlplane instances across all proxmox nodes are not supported
  # https://github.com/ionos-cloud/cluster-api-provider-proxmox/pull/467
  # Once this is merged, I need to edit ProxmoxMachineTemplate to have templateSelector
  # For now, I'l just stick with one controlplane node
  machine:
    hbang-px1:
      templateID: 101
      replicas: 1
      numCores: 4
      numSockets: 1
      memoryMiB: 8192
      diskSizeGb: 100
      format: raw
      fullClone: true
      network:
        bridge: vmbr0
        model: virtio

worker:
  machines:
    hbang-px1:
      templateID: 101
      replicas: 2
      numCores: 4
      numSockets: 1
      memoryMiB: 16384
      diskSizeGb: 100
      format: raw
      fullClone: true
      network:
        bridge: vmbr0
        model: virtio
    hbang-px2:
      templateID: 106
      replicas: 2
      numCores: 4
      numSockets: 1
      memoryMiB: 16384
      diskSizeGb: 100
      format: raw
      fullClone: true
      network:
        bridge: vmbr0
        model: virtio
    hbang-px3:
      templateID: 107
      replicas: 2
      numCores: 4
      numSockets: 1
      memoryMiB: 16384
      diskSizeGb: 100
      format: raw
      fullClone: true
      network:
        bridge: vmbr0
        model: virtio


clusterNetwork:
  pods:
    cidrBlocks:
    - "192.168.0.0/16"

kubeadm:
  initPreKubeadmCommands:
  - "/etc/kube-vip-prepare.sh"
  users:
  - name: root
    sshAuthorizedKeys: []
