{{- if not .Values.proxmox.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "caas.fullname" . }}-proxmox
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "caas.labels" . | nindent 4 }}
stringData:
  url: {{ .Values.proxmox.url | quote }}
  tokenID: {{ .Values.proxmox.tokenID | quote }}
  tokenSecret: {{ .Values.proxmox.tokenSecret | quote }}
{{- end }}
{{- if and .Values.unifi.enabled (not .Values.unifi.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "caas.fullname" . }}-unifi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "caas.labels" . | nindent 4 }}
stringData:
  url: {{ .Values.unifi.url | quote }}
  apiKey: {{ .Values.unifi.apiKey | quote }}
  site: {{ .Values.unifi.site | quote }}
{{- end }}
