{{- range .Values.externalSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  {{- with .template }}
  template:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  secretStoreRef:
    kind: {{ .secretStoreRef.kind }}
    name: {{ .secretStoreRef.name }}
  {{- with .target }}
  target:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  data:
{{ toYaml .data | indent 4 }}
---
{{- end }}

