{{- range .Values.secretStores }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  provider:
{{ toYaml .provider | indent 4 }}
---
{{- end }}
