{{- range $name, $app := .Values.apps }}
{{- if $app.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name }}
  namespace: {{ $.Values.namespace }}
  {{- if $app.serverSideApply }}
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  {{- end }}
spec:
  project: default
  source:
    repoURL: {{ $app.repoURL }}
    targetRevision: {{ default "latest" $app.targetRevision }}
    {{- if $app.path }}
    path: {{ $app.path }}
    {{- else }}
    chart: {{ $app.chart }}
    {{- end }}
    helm:
      releaseName: {{ $app.name }}
      {{- if $app.values }}
      values: |
{{ toYaml $app.values | indent 8 }}
      {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ default $name $app.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}
{{- end }}

