{{- $cluster := .Values.clusterName -}}
{{- $ns := .Values.namespace | default "default" -}}
{{- $k8sVer := .Values.kubernetesVersion -}}
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: KamajiControlPlane
metadata:
  name: {{ printf "%s-control-plane" $cluster }}
  namespace: {{ $ns }}
spec:
  dataStoreName: default
  addons:
    coreDNS: {}
    konnectivity: {}
    kubeProxy: {}
  kubelet:
    cgroupfs: systemd
  network:
    serviceType: LoadBalancer
  version: {{ $k8sVer }}
